# Generated by Django 5.2.1 on 2025-05-07 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_comment_upvote_count_cache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_participant_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed. Null means unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_participants',
            field=models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
