# Generated by Django 5.2.1 on 2025-05-11 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_post_event_participant_limit_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='Private = only community members can join/view'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_private', 'date_time'], name='events_even_is_priv_340482_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_canceled'], name='events_even_is_canc_7b4556_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_e2cef4_idx'),
        ),
    ]
